In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import sqlite3
from core.data import load_from_kaggle

c:\Users\yamen\Desktop\Weiterbildung\visual Studio Code\mein-project\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dataset_link = "saadharoon27/airlines-dataset" # replace with your dataset link from Kaggle 
destination = "../data/raw"
dataset_name = dataset_link.split("/")[-1]

files = load_from_kaggle(
    dataset_link=dataset_link, 
    destination=destination,
    )

Destination directory '../data/raw\airlines-dataset' already exists with files. Skipping download (replace=False).

In [3]:
files

['travel.sqlite']

In [4]:
conn = sqlite3.connect("../data/raw/travel.sqlite")
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tabels = cursor.fetchall()

print(tabels)

[('aircrafts_data',), ('airports_data',), ('boarding_passes',), ('bookings',), ('flights',), ('seats',), ('ticket_flights',), ('tickets',)]

In [5]:
df_aircrafts_data=pd.read_sql_query("SELECT * FROM aircrafts_data", conn)
df_boarding_passes=pd.read_sql_query("SELECT * FROM boarding_passes", conn)
df_bookings=pd.read_sql_query("SELECT * FROM bookings", conn)
df_flights=pd.read_sql_query("SELECT * FROM flights", conn)
df_seats=pd.read_sql_query("SELECT * FROM seats", conn)
df_ticket_flights=pd.read_sql_query("SELECT * FROM ticket_flights", conn)
df_tickets=pd.read_sql_query("SELECT * FROM tickets", conn)
print('aircrafts_data')
display(df_aircrafts_data)
print('\n')
print('boarding_passes')
display(df_boarding_passes)
print('\n')
print('bookings')
display(df_bookings)
print('\n')
print('flights')
display(df_flights)
print('\n')
print('seats')
display(df_seats)
print('\n')
print('ticket_flights')
display(df_ticket_flights)
print('\n')
print('tickets')
display(df_tickets)

aircrafts_data

  aircraft_code                                              model  range
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}  11100
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}   7900
2           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...   3000
3           320  {"en": "Airbus A320-200", "ru": "Аэробус A320-...   5700
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...   5600
5           319  {"en": "Airbus A319-100", "ru": "Аэробус A319-...   6700
6           733    {"en": "Boeing 737-300", "ru": "Боинг 737-300"}   4200
7           CN1  {"en": "Cessna 208 Caravan", "ru": "Сессна 208...   1200
8           CR2  {"en": "Bombardier CRJ-200", "ru": "Бомбардье ...   2700

boarding_passes

            ticket_no  flight_id  boarding_no seat_no
0       0005435212351      30625            1      2D
1       0005435212386      30625            2      3G
2       0005435212381      30625            3      4H
3       0005432211370      30625            4      5D
4       0005435212357      30625            5     11A
...               ...        ...          ...     ...
579681  0005434302871      19945           85     20F
579682  0005432892791      19945           86     21C
579683  0005434302869      19945           87     20E
579684  0005432802476      19945           88     21F
579685  0005432802482      19945           89     21E

[579686 rows x 4 columns]

bookings

       book_ref               book_date  total_amount
0        00000F  2017-07-05 03:12:00+03        265700
1        000012  2017-07-14 09:02:00+03         37900
2        000068  2017-08-15 14:27:00+03         18100
3        000181  2017-08-10 13:28:00+03        131800
4        0002D8  2017-08-07 21:40:00+03         23600
...         ...                     ...           ...
262783   FFFEF3  2017-07-17 07:23:00+03         56000
262784   FFFF2C  2017-08-08 05:55:00+03         10800
262785   FFFF43  2017-07-20 20:42:00+03         78500
262786   FFFFA8  2017-08-08 04:45:00+03         28800
262787   FFFFF7  2017-07-01 22:12:00+03         73600

[262788 rows x 3 columns]

flights

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N
...,...,...,...,...,...,...,...,...,...,...
33116,33117,PG0063,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03
33117,33118,PG0063,2017-07-28 19:25:00+03,2017-07-28 20:10:00+03,SKX,SVO,Arrived,CR2,2017-07-28 19:30:00+03,2017-07-28 20:15:00+03
33118,33119,PG0063,2017-09-08 19:25:00+03,2017-09-08 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N
33119,33120,PG0063,2017-08-01 19:25:00+03,2017-08-01 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-01 19:26:00+03,2017-08-01 20:12:00+03
33120,33121,PG0063,2017-08-26 19:25:00+03,2017-08-26 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N

seats

     aircraft_code seat_no fare_conditions
0              319      2A        Business
1              319      2C        Business
2              319      2D        Business
3              319      2F        Business
4              319      3A        Business
...            ...     ...             ...
1334           773     48H         Economy
1335           773     48K         Economy
1336           773     49A         Economy
1337           773     49C         Economy
1338           773     49D         Economy

[1339 rows x 3 columns]

ticket_flights

             ticket_no  flight_id fare_conditions  amount
0        0005432159776      30625        Business   42100
1        0005435212351      30625        Business   42100
2        0005435212386      30625        Business   42100
3        0005435212381      30625        Business   42100
4        0005432211370      30625        Business   42100
...                ...        ...             ...     ...
1045721  0005435097522      32094         Economy    5200
1045722  0005435097521      32094         Economy    5200
1045723  0005435104384      32094         Economy    5200
1045724  0005435104352      32094         Economy    5200
1045725  0005435104389      32094         Economy    5200

[1045726 rows x 4 columns]

tickets

            ticket_no book_ref passenger_id
0       0005432000987   06B046  8149 604011
1       0005432000988   06B046  8499 420203
2       0005432000989   E170C3  1011 752484
3       0005432000990   E170C3  4849 400049
4       0005432000991   F313DD  6615 976589
...               ...      ...          ...
366728  0005435999869   D730BA  0474 690760
366729  0005435999870   D730BA  6535 751108
366730  0005435999871   A1AD46  1596 156448
366731  0005435999872   7B6A53  9374 822707
366732  0005435999873   7B6A53  7380 075822

[366733 rows x 3 columns]

In [15]:
#join flight information with revenue
sql_query = '''SELECT 
    f.flight_id,
    f.departure_airport,
    f.arrival_airport,
    sum(tf.amount) AS revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY f.flight_id'''
df_join_flight_info_revenue = pd.read_sql_query(sql_query, conn)
display(df_join_flight_info_revenue)

       flight_id departure_airport arrival_airport  revenue
0              1               DME             LED   693700
1              2               DME             LED   867700
2              3               DME             LED   853600
3              5               DME             LED   800800
4              6               DME             LED   868300
...          ...               ...             ...      ...
22221      33117               SKX             SVO    87400
22222      33118               SKX             SVO    86900
22223      33119               SKX             SVO    21600
22224      33120               SKX             SVO    70200
22225      33121               SKX             SVO    98700

[22226 rows x 4 columns]

In [7]:
#join aircraft code with revenue
sql_query ="""SELECT 
    a.aircraft_code,
    SUM(tf.amount) AS revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
JOIN aircrafts_data a 
    ON f.aircraft_code = a.aircraft_code
GROUP BY a.aircraft_code"""
df_join_aircraft_code_revenue=pd.read_sql_query(sql_query, conn)
display(df_join_aircraft_code_revenue)

  aircraft_code     revenue
0           319  2706163100
1           321  1638164100
2           733  1426552100
3           763  4371277100
4           773  3431205500
5           CN1    96373800
6           CR2  1982760500
7           SU9  5114484700

In [9]:
sql_query = """SELECT 
    b.book_ref,
    b.total_amount,
    COUNT(tf.ticket_no) AS tickets
FROM bookings b
JOIN tickets t 
    ON b.book_ref = t.book_ref
JOIN ticket_flights tf 
    ON t.ticket_no = tf.ticket_no
GROUP BY b.book_ref"""

df_total_amount_tickets = pd.read_sql_query(sql_query, conn)
display(df_total_amount_tickets)

       book_ref  total_amount  tickets
0        00000F        265700        2
1        000012         37900        2
2        000068         18100        2
3        000181        131800        8
4        0002D8         23600        2
...         ...           ...      ...
262783   FFFEF3         56000        2
262784   FFFF2C         10800        2
262785   FFFF43         78500        8
262786   FFFFA8         28800        2
262787   FFFFF7         73600        8

[262788 rows x 3 columns]

In [10]:
#calculation of load factor
sql_query = '''with occupied AS (
    SELECT 
        flight_id,
        COUNT(*) AS occupied_seats
    FROM boarding_passes
    GROUP BY flight_id
),

total AS (
    SELECT 
        f.flight_id,
        COUNT(s.seat_no) AS total_seats
    FROM flights f
    JOIN seats s 
        ON f.aircraft_code = s.aircraft_code
    GROUP BY f.flight_id
)

SELECT 
    o.flight_id,
    o.occupied_seats,
    t.total_seats,
    o.occupied_seats * 1.0 / t.total_seats AS load_factor
FROM occupied o
JOIN total t 
    ON o.flight_id = t.flight_id'''

df_load_factor = pd.read_sql_query(sql_query, conn)
display(df_load_factor)

       flight_id  occupied_seats  total_seats  load_factor
0              1              79          170     0.464706
1              2             101          170     0.594118
2              3              97          170     0.570588
3             17             101          170     0.594118
4             18              96          170     0.564706
...          ...             ...          ...          ...
11513      33115              20           50     0.400000
11514      33116              17           50     0.340000
11515      33117              16           50     0.320000
11516      33118              16           50     0.320000
11517      33120              13           50     0.260000

[11518 rows x 4 columns]

In [11]:
#flights with load factor more than 85%
df_load_fctor_over_85 = df_load_factor[df_load_factor['load_factor']>0.8]
display(df_load_fctor_over_85)

       flight_id  occupied_seats  total_seats  load_factor
64           249             365          402     0.907960
65           250             361          402     0.898010
69           259             346          402     0.860697
70           265             323          402     0.803483
72           268             355          402     0.883085
...          ...             ...          ...          ...
11386      32702              45           50     0.900000
11387      32761              11           12     0.916667
11388      32767              12           12     1.000000
11389      32793              11           12     0.916667
11390      32796              12           12     1.000000

[2304 rows x 4 columns]

In [12]:
#calculation of revenue per flight
sql_query = '''SELECT 
    flight_id,
    SUM(amount) AS revenue
FROM ticket_flights
GROUP BY flight_id'''

df_revenue_per_flight = pd.read_sql_query(sql_query, conn)
display(df_revenue_per_flight)

       flight_id  revenue
0              1   693700
1              2   867700
2              3   853600
3              5   800800
4              6   868300
...          ...      ...
22221      33117    87400
22222      33118    86900
22223      33119    21600
22224      33120    70200
22225      33121    98700

[22226 rows x 2 columns]

In [21]:
#comparison of Business vs Economy
sql_query = '''WITH occupied AS (
    SELECT 
        tf.fare_conditions,
        COUNT(*) AS occupied_seats
    FROM boarding_passes bp
    JOIN ticket_flights tf
        ON bp.ticket_no = tf.ticket_no
       AND bp.flight_id = tf.flight_id
    GROUP BY tf.fare_conditions
),

pricing AS (
    SELECT 
        fare_conditions,
        AVG(amount) AS avg_price,
        COUNT(*) AS total_tickets
    FROM ticket_flights
    GROUP BY fare_conditions
)

SELECT 
    p.fare_conditions,
    o.occupied_seats,
    p.total_tickets,
    p.avg_price
FROM pricing p
LEFT JOIN occupied o
    ON p.fare_conditions = o.fare_conditions'''     
df_fare_condition_comparison = pd.read_sql_query(sql_query, conn)
display(df_fare_condition_comparison)

  fare_conditions  occupied_seats  total_tickets     avg_price
0        Business           59479         107642  51143.416139
1         Comfort            9897          17291  32740.552889
2         Economy          510310         920793  15959.813335

In [ ]:
#calculation of revenue per seat
sql_query = '''WITH revenue AS (
    SELECT 
        flight_id,
        SUM(amount) AS total_revenue
    FROM ticket_flights
    GROUP BY flight_id
),

seats_total AS (
    SELECT 
        f.flight_id,
        COUNT(s.seat_no) AS total_seats
    FROM flights f
    JOIN seats s 
        ON f.aircraft_code = s.aircraft_code
    GROUP BY f.flight_id
)

SELECT 
    r.flight_id,
    r.total_revenue,
    s.total_seats,
    r.total_revenue * 1.0 / s.total_seats AS revenue_per_seat
FROM revenue r
JOIN seats_total s 
    ON r.flight_id = s.flight_id
ORDER BY revenue_per_seat DESC'''

df_revenue_per_seat = pd.read_sql_query(sql_query, conn)
display(df_revenue_per_seat)

       flight_id  total_revenue  total_seats  revenue_per_seat
0           2354       17146600          222      77236.936937
1          26212       17023600          222      76682.882883
2           2364       16962100          222      76405.855856
3           2330       16900600          222      76128.828829
4           2329       16894400          222      76100.900901
...          ...            ...          ...               ...
22221      14672           3200           97         32.989691
22222      14714           3200           97         32.989691
22223      10602           3000           97         30.927835
22224      10653           3000           97         30.927835
22225      27684           3000           97         30.927835

[22226 rows x 4 columns]

In [19]:
#binding revenue per seat with the type of aircraft
sql_query = '''
WITH revenue AS (
    SELECT 
        f.flight_id,
        f.aircraft_code,
        SUM(tf.amount) AS total_revenue
    FROM ticket_flights tf
    JOIN flights f ON tf.flight_id = f.flight_id
    GROUP BY f.flight_id, f.aircraft_code
),

seats_total AS (
    SELECT 
        aircraft_code,
        COUNT(seat_no) AS total_seats
    FROM seats
    GROUP BY aircraft_code
)

SELECT 
    r.aircraft_code,
    AVG(r.total_revenue * 1.0 / s.total_seats) AS avg_revenue_per_seat,
    a.model
FROM revenue r
JOIN seats_total s 
    ON r.aircraft_code = s.aircraft_code
JOIN  aircrafts_data a
    ON r.aircraft_code = a.aircraft_code
GROUP BY r.aircraft_code, a.model
ORDER BY avg_revenue_per_seat DESC'''
df_revenue_per_seat_aircraft = pd.read_sql_query(sql_query, conn)
display(df_revenue_per_seat_aircraft)

,aircraft_code,avg_revenue_per_seat,model
0,319,21864.097696,"{""en"": ""Airbus A319-100"", ""ru"": ""Аэробус A319-..."
1,763,16477.353462,"{""en"": ""Boeing 767-300"", ""ru"": ""Боинг 767-300""}"
2,773,14015.331797,"{""en"": ""Boeing 777-300"", ""ru"": ""Боинг 777-300""}"
3,733,9427.386334,"{""en"": ""Boeing 737-300"", ""ru"": ""Боинг 737-300""}"
4,SU9,7607.364939,"{""en"": ""Sukhoi Superjet-100"", ""ru"": ""Сухой Суп..."
5,321,7446.877443,"{""en"": ""Airbus A321-200"", ""ru"": ""Аэробус A321-..."
6,CR2,5341.488416,"{""en"": ""Bombardier CRJ-200"", ""ru"": ""Бомбардье ..."
7,CN1,3159.382376,"{""en"": ""Cessna 208 Caravan"", ""ru"": ""Сессна 208..."

In [33]:
#anaylying of time of flights
sql_query = '''SELECT 
    strftime('%Y-%m-%d', substr(f.scheduled_departure, 1, 19)) AS year_month_day,
    COUNT(tf.ticket_no) AS total_tickets,
    SUM(tf.amount) AS total_revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY year_month_day
ORDER BY year_month_day'''
df_departure_time = pd.read_sql_query(sql_query, conn)
display(df_departure_time)

   year_month_day  total_tickets  total_revenue
0      2017-07-16           8335      166633500
1      2017-07-17          10893      215387900
2      2017-07-18          11492      223835400
3      2017-07-19          11409      225519700
4      2017-07-20          11693      235133300
..            ...            ...            ...
56     2017-09-10           5430      101704700
57     2017-09-11           4038       75325800
58     2017-09-12           2952       57207500
59     2017-09-13           2048       34377400
60     2017-09-14            854       16546800

[61 rows x 3 columns]

In [32]:
#analysing of time in weekdays
sql_query = '''SELECT 
    strftime('%w', substr(f.scheduled_departure, 1, 19)) AS weekday_number,
    
    CASE strftime('%w', substr(f.scheduled_departure, 1, 19))
        WHEN '0' THEN 'Sonntag'
        WHEN '1' THEN 'Montag'
        WHEN '2' THEN 'Dienstag'
        WHEN '3' THEN 'Mittwoch'
        WHEN '4' THEN 'Donnerstag'
        WHEN '5' THEN 'Freitag'
        WHEN '6' THEN 'Samstag'
    END AS weekday_name,

    COUNT(tf.ticket_no) AS total_tickets,
    SUM(tf.amount) AS total_revenue,
    COUNT(DISTINCT f.flight_id) AS total_flights

FROM flights f
JOIN ticket_flights tf
    ON f.flight_id = tf.flight_id

GROUP BY weekday_number
ORDER BY weekday_number'''
df_departure_week_days = pd.read_sql_query(sql_query, conn)
display(df_departure_week_days)

  weekday_number weekday_name  total_tickets  total_revenue  total_flights
0              0      Sonntag         153136     3046656500           3372
1              1       Montag         150442     2995167500           3190
2              2     Dienstag         153804     3033617000           3338
3              3     Mittwoch         149907     2965519400           3236
4              4   Donnerstag         150094     3006934300           3180
5              5      Freitag         141574     2721115600           2803
6              6      Samstag         146769     2997970600           3107

In [34]:
#anaylying of time of flights in hours
sql_query = '''SELECT 
    strftime('%H', substr(f.scheduled_departure, 1, 19)) AS hour,
    COUNT(tf.ticket_no) AS total_tickets,
    SUM(tf.amount) AS total_revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY hour'''
df_departure_time_hour= pd.read_sql_query(sql_query, conn)
display(df_departure_time_hour)

   hour  total_tickets  total_revenue
0    02           4227       42652600
1    03           1584       82398900
2    04           7347      440528800
3    05           9837      664052700
4    06           9156      198891900
5    07          28673      584841100
6    08          39693      718313200
7    09         106563     2479985800
8    10         101906     1824375200
9    11         139148     2974993400
10   12          84888     1949481400
11   13          84289     1349557400
12   14          95815     1476937600
13   15          91075     1217098600
14   16          42964      553865100
15   17          66505     1190128500
16   18          77556     1059932300
17   19          41244      912768900
18   20          13256     1046177500